```mmd
flowchart LR
N_MainActivity["MainActivity"]
N_onCreate["onCreate"]
N_MarsPhotosApplication["MarsPhotosApplication"]
N_MarsViewModelTest["MarsViewModelTest"]
N_marsViewModel_getMarsPhotos_verifyMarsUiStateSuccess["marsViewModel_getMarsPhotos_verifyMarsUiStateSuccess"]
N_NetworkMarsRepositoryTest["NetworkMarsRepositoryTest"]
N_networkMarsPhotosRepository_getMarsPhotos_verifyPhotoList["networkMarsPhotosRepository_getMarsPhotos_verifyPhotoList"]
N_AppContainer["AppContainer"]
N_DefaultAppContainer["DefaultAppContainer"]
N_MarsPhotosRepository["MarsPhotosRepository"]
N_NetworkMarsPhotosRepository["NetworkMarsPhotosRepository"]
N_getMarsPhotos["getMarsPhotos"]
N_MarsPhoto["MarsPhoto"]
N_MarsApiService["MarsApiService"]
N_getPhotos["getPhotos"]
N_MarsPhotosApp["MarsPhotosApp"]
N_MarsTopAppBar["MarsTopAppBar"]
N_FakeDataSource["FakeDataSource"]
N_FakeMarsApiService["FakeMarsApiService"]
N_FakeNetworkMarsPhotosRepository["FakeNetworkMarsPhotosRepository"]
N_TestDispatcherRule["TestDispatcherRule"]
N_starting["starting"]
N_finished["finished"]
N_HomeScreen["HomeScreen"]
N_LoadingScreen["LoadingScreen"]
N_ErrorScreen["ErrorScreen"]
N_PhotosGridScreen["PhotosGridScreen"]
N_MarsPhotoCard["MarsPhotoCard"]
N_LoadingScreenPreview["LoadingScreenPreview"]
N_ErrorScreenPreview["ErrorScreenPreview"]
N_PhotosGridScreenPreview["PhotosGridScreenPreview"]
N_MarsUiState["MarsUiState"]
N_Success["Success"]
N_Error["Error"]
N_Loading["Loading"]
N_MarsViewModel["MarsViewModel"]
N_MarsPhotosTheme["MarsPhotosTheme"]
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_MainActivity_kt --> N_onCreate
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_MainActivity_kt --> N_MarsPhotosTheme
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_MainActivity_kt --> N_MarsPhotosApp
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_MarsPhotosApplication_kt --> N_onCreate
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_MarsPhotosApplication_kt --> N_DefaultAppContainer
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_MarsViewModelTest_kt --> N_TestDispatcherRule
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_MarsViewModelTest_kt --> N_MarsViewModel
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_MarsViewModelTest_kt --> N_FakeNetworkMarsPhotosRepository
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_MarsViewModelTest_kt --> N_Success
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_NetworkMarsRepositoryTest_kt --> N_NetworkMarsPhotosRepository
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_NetworkMarsRepositoryTest_kt --> N_FakeMarsApiService
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_NetworkMarsRepositoryTest_kt --> N_getMarsPhotos
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_data_AppContainer_kt --> N_NetworkMarsPhotosRepository
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_data_MarsPhotosRepository_kt --> N_getPhotos
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_MarsPhotosApp_kt --> N_MarsTopAppBar
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_MarsPhotosApp_kt --> N_HomeScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_fake_FakeDataSource_kt --> N_MarsPhoto
F_E__myProjects_lyx_convertTestAndroid_app_src_test_java_com_example_marsphotos_fake_FakeDataSource_kt --> N_MarsPhoto
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_LoadingScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_PhotosGridScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_ErrorScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_MarsPhotoCard
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_MarsPhotosTheme
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_LoadingScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_MarsPhotosTheme
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_ErrorScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_MarsPhotosTheme
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_MarsPhoto
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_HomeScreen_kt --> N_PhotosGridScreen
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_MarsViewModel_kt --> N_getMarsPhotos
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_MarsViewModel_kt --> N_Success
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_MarsViewModel_kt --> N_getMarsPhotos
F_E__myProjects_lyx_convertTestAndroid_app_src_main_java_com_example_marsphotos_ui_screens_MarsViewModel_kt --> N_MarsViewModel
```